services:
  headscale-oidc-sync:
    image: ${REPOSITORY}/jgy/headscale-oidc-sync
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acl.json:/workspace/acl.json